# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ :name => 'Chicago' }, { :name => 'Copenhagen' }])
#   Mayor.create(:name => 'Emanuel', :city => cities.first)
    State.create([
                 {:name => 'Indiana'}, 
                 {:name => 'Illinois'}
    ])
    County.create([
                 {:name => 'Adams', :state_id => 1},
                 {:name => 'Allen', :state_id => 1},
                 {:name => 'Bartholomew', :state_id => 1},
                 {:name => 'Benton', :state_id => 1},
                 {:name => 'Blackford', :state_id => 1},
                 {:name => 'Boone', :state_id => 1},
                 {:name => 'Brown', :state_id => 1},
                 {:name => 'Carroll', :state_id => 1},
                 {:name => 'Cass', :state_id => 1},
                 {:name => 'Clark', :state_id => 1},
                 {:name => 'Clay', :state_id => 1},
                 {:name => 'Clinton', :state_id => 1},
                 {:name => 'Crawford', :state_id => 1},
                 {:name => 'Daviess', :state_id => 1},
                 {:name => 'Dearborn', :state_id => 1},
                 {:name => 'Decatur', :state_id => 1},
                 {:name => 'DeKalb', :state_id => 1},
                 {:name => 'Delaware', :state_id => 1},
                 {:name => 'Dubois', :state_id => 1},
                 {:name => 'Elkhart', :state_id => 1},
                 {:name => 'Fayette', :state_id => 1},
                 {:name => 'Floyd', :state_id => 1},
                 {:name => 'Fountain', :state_id => 1},
                 {:name => 'Franklin', :state_id => 1},
                 {:name => 'Fulton', :state_id => 1},
                 {:name => 'Gibson', :state_id => 1},
                 {:name => 'Grant', :state_id => 1},
                 {:name => 'Greene', :state_id => 1},
                 {:name => 'Hamilton', :state_id => 1},
                 {:name => 'Hancock', :state_id => 1},
                 {:name => 'Harrison', :state_id => 1},
                 {:name => 'Hendricks', :state_id => 1},
                 {:name => 'Henry', :state_id => 1},
                 {:name => 'Howard', :state_id => 1},
                 {:name => 'Huntington', :state_id => 1},
                 {:name => 'Jackson', :state_id => 1},
                 {:name => 'Jasper', :state_id => 1},
                 {:name => 'Jay', :state_id => 1},
                 {:name => 'Jefferson', :state_id => 1},
                 {:name => 'Jennings', :state_id => 1},
                 {:name => 'Johnson', :state_id => 1},
                 {:name => 'Knox', :state_id => 1},
                 {:name => 'Kosciusko', :state_id => 1},
                 {:name => 'LaGrange', :state_id => 1},
                 {:name => 'Lake', :state_id => 1},
                 {:name => 'LaPorte', :state_id => 1},
                 {:name => 'Lawrence', :state_id => 1},
                 {:name => 'Madison', :state_id => 1},
                 {:name => 'Marion', :state_id => 1},
                 {:name => 'Marshall', :state_id => 1},
                 {:name => 'Martin', :state_id => 1},
                 {:name => 'Miami', :state_id => 1},
                 {:name => 'Montgomery', :state_id => 1},
                 {:name => 'Monroe', :state_id => 1},
                 {:name => 'Morgan', :state_id => 1},
                 {:name => 'Newton', :state_id => 1},
                 {:name => 'Noble', :state_id => 1},
                 {:name => 'Ohio', :state_id => 1},
                 {:name => 'Orange', :state_id => 1},
                 {:name => 'Owen', :state_id => 1},
                 {:name => 'Parke', :state_id => 1},
                 {:name => 'Perry', :state_id => 1},
                 {:name => 'Pike', :state_id => 1},
                 {:name => 'Porter', :state_id => 1},
                 {:name => 'Posey', :state_id => 1},
                 {:name => 'Pulaski', :state_id => 1},
                 {:name => 'Putnam', :state_id => 1},
                 {:name => 'Randolph', :state_id => 1},
                 {:name => 'Ripley', :state_id => 1},
                 {:name => 'Rush', :state_id => 1},
                 {:name => 'Scott', :state_id => 1},
                 {:name => 'Shelby', :state_id => 1},
                 {:name => 'Spencer', :state_id => 1},
                 {:name => 'St. Joseph', :state_id => 1},
                 {:name => 'Starke', :state_id => 1},
                 {:name => 'Steuben', :state_id => 1},
                 {:name => 'Sullivan', :state_id => 1},
                 {:name => 'Switzerland', :state_id => 1},
                 {:name => 'Tippecanoe', :state_id => 1},
                 {:name => 'Tipton', :state_id => 1},
                 {:name => 'Union', :state_id => 1},
                 {:name => 'Vanderburgh', :state_id => 1},
                 {:name => 'Vermillion', :state_id => 1},
                 {:name => 'Vigo', :state_id => 1},
                 {:name => 'Wabash', :state_id => 1},
                 {:name => 'Warren', :state_id => 1},
                 {:name => 'Warrick', :state_id => 1},
                 {:name => 'Washington', :state_id => 1},
                 {:name => 'Wayne', :state_id => 1},
                 {:name => 'Wells', :state_id => 1},
                 {:name => 'White', :state_id => 1},
                 {:name => 'Whitley', :state_id => 1}
    ])
